### ISSUE TITLE
QVTKWidget is not available 

### ISSUE THREAD

**Issue by altaybrusan** [commontk/CTK#777]
Based on:
 https://www.slicer.org/wiki/Documentation/Labs/Qt5-and-VTK8#List_of_fixes_integrated_into_VTK

There is no need to add any thing to CTK source code. But, I got this error:

moc_ctkVTKMagnifyView.cpp: error C2061: syntax error: identifier 'QVTKWidget'

The wiered thing is that the moc file shows this error. However, the cpp and .h files have no error at all!!!

PS: configuration is VTK 8.0 (with openGl2 backend) QT 5.8 and visual studio 2015 x64

**Comment by jcfr** [comment]
@altaybrusan Thanks for report

Could you provide here the the command allowing to reproduce the issue ? 

Ideally, you would provide a `reproduce_ctk_issue.bat` script like this one:

```
set VTK_DIR=C:\path\to\VTK-Release
set QT5_DIR=C:\path\to\lib/cmake\Qt5

git clone git://github.com/kitware/VTK
cd VTK
git checkout vX.Y.Z
cd ..
mkdir VTK-build
cd VTK-build
cmake -DQt5_DIR:PATH=% QT5_DIR% ^
      -DBUILD_TESTING:BOOL=OFF ^
      -DBUILD_EXAMPLES:BOOL=OFF ^
      -DBUILD_SHARED_LIBS:BOOL=ON ^
      -DVTK_QT_VERSION:STRING=5 ^
      List here all options    <-----------------------
..\VTK

cmake --build . --config Release -- /m

cd ..

git clone git://github.com/commontk/CTK
mkdir CTK-build
cmake -DQt5_DIR:PATH=% QT5_DIR% ^
  -DCTK_QT_VERSION:STRING=5 ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DCTK_LIB_Widgets:BOOL=ON ^
  -DCTK_LIB_Visualization/VTK/Widgets:BOOL=ON ^
  -DVTK_DIR:PATH=%VTK_DIR% ^
  List here all options    <-----------------------
..\CTK

cmake --build . --config Release -- /m
```

**Comment by altaybrusan** [comment]
hi, I tried for the last few days to get the complete list:

set VTK_DIR=C:\VTK8-backup
set QT5_DIR=C:\Qt\Qt5.8.0\5.8\msvc2015_64\lib\cmake\Qt5
git clone https://github.com/Kitware/VTK.git
cd VTK
git checkout v8.0.1
cd ..
mkdir VTK-build
cd VTK-build
cmake -G "Visual Studio 14 2015 Win64" ^
      -DQt5_DIR:PATH=% QT5_DIR% ^
      -DBUILD_TESTING:BOOL=OFF ^
      -DBUILD_EXAMPLES:BOOL=OFF ^
      -DBUILD_SHARED_LIBS:BOOL=ON ^
      -DVTK_QT_VERSION:STRING=5 ^
      -DBUILD_DOCUMENTATION:BOOL=OFF^
      -DBUILD_USER_DEFINED_LIBS:BOOL=OFF^
      -DEXECUTABLE_OUTPUT_PATH:PATH=^
      -DEXODUSII_DISABLE_COMPILER_WARNINGS:BOOL=ON^
      -DExternalData_URL_TEMPLATES:STRING=^
      -DHAVE_IEEEFP:STRING=1^
      -DHDF5_BUILD_STATIC_EXECS:BOOL=OFF^
      -DHDF5_ENABLE_ALL_WARNINGS:BOOL=OFF^
      -DHDF5_ENABLE_DEBUG_APIS:BOOL=OFF^
      -DHDF5_ENABLE_EMBEDDED_LIBINFO:BOOL=ON^
      -DHDF5_ENABLE_GROUPFIVE_WARNINGS:BOOL=OFF^
      -DHDF5_ENABLE_GROUPFOUR_WARNINGS:BOOL=OFF^
      -DHDF5_ENABLE_GROUPONE_WARNINGS:BOOL=OFF^
      -DHDF5_ENABLE_GROUPTHREE_WARNINGS:BOOL=OFF^
      -DHDF5_ENABLE_GROUPTWO_WARNINGS:BOOL=OFF^
      -DHDF5_ENABLE_GROUPZERO_WARNINGS:BOOL=OFF^
      -DHDF5_NO_PACKAGES:BOOL=OFF^
      -DHDF5_PACK_EXAMPLES:BOOL=OFF^
      -DHDF5_USE_FOLDERS:BOOL=ON^
      -DHOST_BIG_ENDIAN:STRING=OFF^
      -DHOST_FILLORDER:STRING=FILLORDER_MSB2LSB^
      -DLIBPROJ_BINDIR:PATH=bin^
      -DLIBPROJ_DATADIR:PATH=share^
      -DLIBPROJ_DOCDIR:PATH=share/doc/proj^
      -DLIBPROJ_INCLUDEDIR:PATH=local/include^
      -DLIBPROJ_LIBDIR:PATH=local/lib^
      -DLIBPROJ_USE_THREAD:BOOL=ON^
      -DLIBRARY_OUTPUT_PATH:PATH=^
      -DM_LIBRARY:FILEPATH=M_LIBRARY-NOTFOUND^
      -DModule_AutobahnPython:BOOL=OFF^
      -DModule_PoissonReconstruction:BOOL=OFF^
      -DModule_SignedTensor:BOOL=OFF^
      -DModule_SixPython:BOOL=OFF^
      -DModule_SplineDrivenImageSlicer:BOOL=OFF^
      -DModule_Twisted:BOOL=OFF^
      -DModule_WikiExamples:BOOL=OFF^
      -DModule_ZopeInterface:BOOL=OFF^
      -DModule_constantly:BOOL=OFF^
      -DModule_incremental:BOOL=OFF^
      -DModule_vtkAcceleratorsVTKm:BOOL=OFF^
      -DModule_vtkAddon:BOOL=OFF^
      -DModule_vtkDICOM:BOOL=OFF^
      -DModule_vtkDomainsMicroscopy:BOOL=OFF^
      -DModule_vtkFiltersMatlab:BOOL=OFF^
      -DModule_vtkFiltersParallelFlowPaths:BOOL=OFF^
      -DModule_vtkFiltersParallelGeometry:BOOL=OFF^
      -DModule_vtkFiltersParallelMPI:BOOL=OFF^
      -DModule_vtkFiltersParallelStatistics:BOOL=OFF^
      -DModule_vtkFiltersReebGraph:BOOL=OFF^
      -DModule_vtkFiltersStatisticsGnuR:BOOL=OFF^
      -DModule_vtkGUISupportMFC:BOOL=OFF^
      -DModule_vtkGUISupportQtWebkit:BOOL=OFF^
      -DModule_vtkIOADIOS:BOOL=OFF^
      -DModule_vtkIOFFMPEG:BOOL=OFF^
      -DModule_vtkIOGDAL:BOOL=OFF^
      -DModule_vtkIOGeoJSON:BOOL=OFF^
      -DModule_vtkIOMPIImage:BOOL=OFF^
      -DModule_vtkIOMPIParallel:BOOL=OFF^
      -DModule_vtkIOMySQL:BOOL=OFF^
      -DModule_vtkIOODBC:BOOL=OFF^
      -DModule_vtkIOParallelExodus:BOOL=OFF^
      -DModule_vtkIOParallelLSDyna:BOOL=OFF^
      -DModule_vtkIOParallelNetCDF:BOOL=OFF^
      -DModule_vtkIOPostgreSQL:BOOL=OFF^
      -DModule_vtkIOVPIC:BOOL=OFF^
      -DModule_vtkIOXdmf2:BOOL=OFF^
      -DModule_vtkIOXdmf3:BOOL=OFF^
      -DModule_vtkInfovisBoost:BOOL=OFF^
      -DModule_vtkInfovisBoostGraphAlgorithms:BOOL=OFF^
      -DModule_vtkInfovisParallel:BOOL=OFF^
      -DModule_vtkParallelMPI:BOOL=OFF^
      -DModule_vtkPython:BOOL=OFF^
      -DModule_vtkPythonInterpreter:BOOL=OFF^
      -DModule_vtkRenderingExternal:BOOL=OFF^
      -DModule_vtkRenderingFreeTypeFontConfig:BOOL=OFF^
      -DModule_vtkRenderingMatplotlib:BOOL=OFF^
      -DModule_vtkRenderingOSPRay:BOOL=OFF^
      -DModule_vtkRenderingParallel:BOOL=OFF^
      -DModule_vtkRenderingParallelLIC:BOOL=OFF^
      -DModule_vtkRenderingSceneGraph:BOOL=OFF^
      -DModule_vtkRenderingTk:BOOL=OFF^
      -DModule_vtkRenderingVolumeAMR:BOOL=OFF^
      -DModule_vtkTclTk:BOOL=OFF^
      -DModule_vtkTestingCore:BOOL=OFF^
      -DModule_vtkTestingGenericBridge:BOOL=OFF^
      -DModule_vtkTestingIOSQL:BOOL=OFF^
      -DModule_vtkTestingRendering:BOOL=OFF^
      -DModule_vtkUtilitiesBenchmarks:BOOL=OFF^
      -DModule_vtkVPIC:BOOL=OFF^
      -DModule_vtkViewsGeovis:BOOL=OFF^
      -DModule_vtkWebCore:BOOL=OFF^
      -DModule_vtkWebGLExporter:BOOL=OFF^
      -DModule_vtkWebPython:BOOL=OFF^
      -DModule_vtkWrappingJava:BOOL=OFF^
      -DModule_vtkWrappingPythonCore:BOOL=OFF^
      -DModule_vtkWrappingTcl:BOOL=OFF^
      -DModule_vtkWrappingTools:BOOL=OFF^
      -DModule_vtkglew:BOOL=OFF^
      -DModule_vtkmpi4py:BOOL=OFF^
      -DModule_vtkxdmf2:BOOL=OFF^
      -DModule_vtkxdmf3:BOOL=OFF^
      -DModule_vtkzfp:BOOL=OFF^
      -DNETCDF4_CHUNK_CACHE_NELEMS:STRING=1009^
      -DNETCDF4_CHUNK_CACHE_PREEMPTION:STRING=0.75^
      -DNETCDF4_CHUNK_CACHE_SIZE:STRING=4194304^
      -DNETCDF4_DEFAULT_CHUNKS_IN_CACHE:STRING=10^
      -DNETCDF4_DEFAULT_CHUNK_SIZE:STRING=4194304^
      -DNETCDF4_MAX_DEFAULT_CACHE_SIZE:STRING=67108864^
      -DOPENGL_gl_LIBRARY:STRING=opengl32^
      -DOPENGL_glu_LIBRARY:STRING=glu32^
      -DPROJ_BIN_SUBDIR:STRING=bin^
      -DPROJ_DATA_SUBDIR:STRING=share^
      -DPROJ_LIB_SUBDIR:STRING=local/lib^
      -DUSE_COMPILER_HIDDEN_VISIBILITY:BOOL=ON^
      -DVTKOGGTHEORA_DISABLE_ASM:BOOL=OFF^
      -DVTKOGGTHEORA_DISABLE_FLOAT:BOOL=OFF^
      -DVTKOGGTHEORA_SHARED_LINKER_FLAGS:STRING=^
      -DVTK_ALL_NEW_OBJECT_FACTORY:BOOL=OFF^
      -DVTK_ANDROID_BUILD:BOOL=OFF^
      -DVTK_BUILD_ALL_MODULES:BOOL=OFF^
      -DVTK_BUILD_PYTHON_MODULE_DIR:PATH=-NOTFOUND^
      -DVTK_BUILD_QT_DESIGNER_PLUGIN:BOOL=ON^
      -DVTK_DATA_EXCLUDE_FROM_ALL:BOOL=OFF^
      -DVTK_DATA_STORE:PATH=^
      -DVTK_DEBUG_LEAKS:BOOL=OFF^
      -DVTK_DISPATCH_AOS_ARRAYS:BOOL=ON^
      -DVTK_DISPATCH_SOA_ARRAYS:BOOL=OFF^
      -DVTK_DISPATCH_TYPED_ARRAYS:BOOL=OFF^
      -DVTK_EGL_DEVICE_INDEX:STRING=0^
      -DVTK_ENABLE_KITS:BOOL=OFF^
      -DVTK_EXTERNAL_LIBHARU_IS_SHARED:BOOL=ON^
      -DVTK_FORBID_DOWNLOADS:BOOL=OFF^
      -DVTK_Group_Imaging:BOOL=OFF^
      -DVTK_Group_MPI:BOOL=OFF^
      -DVTK_Group_Qt:BOOL=ON^
      -DVTK_Group_Rendering:BOOL=ON^
      -DVTK_Group_StandAlone:BOOL=ON^
      -DVTK_Group_Tk:BOOL=OFF^
      -DVTK_Group_Views:BOOL=OFF^
      -DVTK_Group_Web:BOOL=OFF^
      -DVTK_INSTALL_PYTHON_MODULE_DIR:PATH=-NOTFOUND^
      -DVTK_INSTALL_QT_PLUGIN_DIR:STRING=${CMAKE_INSTALL_PREFIX}/${VTK_INSTALL_QT_DIR}^
      -DVTK_IOS_BUILD:BOOL=OFF^
      -DVTK_LEGACY_REMOVE:BOOL=OFF^
      -DVTK_LEGACY_SILENT:BOOL=OFF^
      -DVTK_MAKE_INSTANTIATORS:BOOL=OFF^
      -DVTK_MAX_THREADS:STRING=64^
      -DVTK_OPENGL_HAS_OSMESA:BOOL=OFF^
      -DVTK_PYTHON_VERSION:STRING=2^
      -DVTK_QT_VERSION:STRING=5^
      -DVTK_RENDERING_BACKEND:STRING=OpenGL2^
      -DVTK_REPORT_OPENGL_ERRORS:BOOL=ON^
      -DVTK_REPORT_OPENGL_ERRORS_IN_RELEASE_BUILDS:BOOL=OFF^
      -DVTK_SMP_IMPLEMENTATION_TYPE:STRING=Sequential^
      -DVTK_USE_64BIT_IDS:BOOL=ON^
      -DVTK_USE_LARGE_DATA:BOOL=OFF^
      -DVTK_USE_OFFSCREEN:BOOL=OFF^
      -DVTK_USE_OFFSCREEN_EGL:BOOL=OFF^
      -DVTK_USE_SYSTEM_EXPAT:BOOL=OFF^
      -DVTK_USE_SYSTEM_FREETYPE:BOOL=OFF^
      -DVTK_USE_SYSTEM_GL2PS:BOOL=OFF^
      -DVTK_USE_SYSTEM_GLEW:BOOL=OFF^
      -DVTK_USE_SYSTEM_HDF5:BOOL=OFF^
      -DVTK_USE_SYSTEM_JPEG:BOOL=OFF^
      -DVTK_USE_SYSTEM_JSONCPP:BOOL=OFF^
      -DVTK_USE_SYSTEM_LIBHARU:BOOL=OFF^
      -DVTK_USE_SYSTEM_LIBPROJ4:BOOL=OFF^
      -DVTK_USE_SYSTEM_LIBRARIES:BOOL=OFF^
      -DVTK_USE_SYSTEM_LIBXML2:BOOL=OFF^
      -DVTK_USE_SYSTEM_LZ4:BOOL=OFF^
      -DVTK_USE_SYSTEM_NETCDF:BOOL=OFF^
      -DVTK_USE_SYSTEM_NETCDFCPP:BOOL=OFF^
      -DVTK_USE_SYSTEM_OGGTHEORA:BOOL=OFF^
      -DVTK_USE_SYSTEM_PNG:BOOL=OFF^
      -DVTK_USE_SYSTEM_TIFF:BOOL=OFF^
      -DVTK_USE_SYSTEM_ZLIB:BOOL=OFF^
      -DVTK_USE_TDX:BOOL=OFF^
      -DVTK_USE_VIDEO_FOR_WINDOWS:BOOL=ON^
      -DVTK_USE_X:BOOL=OFF^
      -DVTK_WARN_ON_DISPATCH_FAILURE:BOOL=OFF^
      -DVTK_WRAP_JAVA:BOOL=OFF^
      -DVTK_WRAP_PYTHON:BOOL=OFF^
      -DVTK_WRAP_TCL:BOOL=OFF^
      -DBUILD_DOCUMENTATION:BOOL=OFF^
      -DBUILD_DOCUMENTATION:BOOL=OFF^
      -DBUILD_DOCUMENTATION:BOOL=OFF^
      -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.4^
      -DCMAKE_CONFIGURATION_TYPES:STRING=Debug;Release^
     ..\VTK

cmake --build . --config Release -- /m

cd ..

echo:off ------------------------- CTK MAKE IS STARTED

git clone git://github.com/commontk/CTK
cd CTK
git checkout master
cd ..

cd CTK
cmake -G "Visual Studio 14 2015 Win64" ^
  -DQt5_DIR:PATH=% QT5_DIR% ^
  -DCTK_QT_VERSION:STRING=5 ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DCTK_LIB_Widgets:BOOL=ON ^
  -DCTK_LIB_Visualization/VTK/Widgets:BOOL=ON ^
  -DVTK_DIR:PATH=%VTK_DIR% ^  
  -DBUILD_TESTING:BOOL=OFF ^
  -DCMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;MinSizeRel;RelWithDebInfo ^
  -DCMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc ^
  -DCMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1^
  -DCMAKE_C_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib ^
  -DCMAKE_EXE_LINKER_FLAGS:STRING=/machine:x64 ^
  -DCMAKE_MODULE_LINKER_FLAGS:STRING=/machine:x64 ^
  -DCMAKE_INSTALL_PREFIX:PATH=C:/temp/Ctk-ins ^
  -DCMAKE_RC_FLAGS:STRING=/DWIN32 ^
  -DCMAKE_RC_FLAGS_DEBUG:STRING=/D_DEBUG ^
  -CMAKE_VERBOSE_MAKEFILE:BOOL=OFF ^
  -DCTEST_SUBMIT_RETRY_COUNT:STRING=3 ^
  -DCTEST_SUBMIT_RETRY_DELAY:STRING=5 ^
  -DCTK_APP_ctkCommandLineModuleExplorer:BOOL=OFF^
  -DCTK_APP_ctkDICOM:BOOL=OFF ^
  -DCTK_APP_ctkDICOM2:BOOL=OFF ^
  -DCTK_APP_ctkDICOMDemoSCU:BOOL=OFF ^
  -DCTK_APP_ctkDICOMHost:BOOL=OFF ^
  -DCTK_APP_ctkDICOMIndexer:BOOL=OFF ^
  -DCTK_APP_ctkDICOMObjectViewer:BOOL=OFF ^
  -DCTK_APP_ctkDICOMQuery:BOOL=OFF ^
  -DCTK_APP_ctkDICOMQueryRetrieve:BOOL=OFF ^
  -DCTK_APP_ctkDICOMRetrieve:BOOL=OFF ^
  -DCTK_APP_ctkExampleHost:BOOL=OFF ^
  -DCTK_APP_ctkExampleHostedApp:BOOL=OFF ^
  -DCTK_APP_ctkPluginBrowser:BOOL=OFF ^
  -DCTK_APP_ctkPluginGenerator:BOOL=OFF ^
  -DCTK_APP_ctkSimplePythonShell:BOOL=OFF ^
  -DCTK_APP_ctkXnatTreeBrowser:BOOL=OFF ^
  -DCTK_BINARY_DIR:STATIC=C:/temp/CTK-bin ^
  -DCTK_BUILD_ALL:BOOL=OFF ^
  -DCTK_BUILD_ALL_APPS:BOOL=OFF ^
  -DCTK_BUILD_ALL_LIBRARIES:BOOL=OFF ^
  -DCTK_BUILD_ALL_PLUGINS:BOOL=OFF ^
  -DCTK_BUILD_EXAMPLES:BOOL=OFF ^
  -DCTK_BUILD_QTDESIGNER_PLUGINS:BOOL=ON ^
  -DCTK_BUILD_SHARED_LIBS:BOOL=ON ^
  -DCTK_ENABLE_DICOM:BOOL=OFF ^
  -DCTK_ENABLE_DICOMApplicationHosting:BOOL=OFF ^
  -DCTK_ENABLE_PluginFramework:BOOL=OFF ^
  -DCTK_ENABLE_Python_Wrapping:BOOL=OFF ^
  -DCTK_ENABLE_Widgets:BOOL=ON ^
  -DCTK_LIB_CommandLineModules/Backend/FunctionPointer:BOOL=OFF ^
  -DCTK_LIB_CommandLineModules/Backend/LocalProcess:BOOL=OFF ^
  -DCTK_LIB_CommandLineModules/Backend/XMLChecker:BOOL=OFF ^
  -DCTK_LIB_CommandLineModules/Core:BOOL=OFF ^
  -DCTK_LIB_CommandLineModules/Frontend/QtGui:BOOL=OFF ^
  -DCTK_LIB_CommandLineModules/Frontend/QtWebKit:BOOL=OFF ^
  -DCTK_LIB_Core:BOOL=ON ^
  -DCTK_LIB_Core_WITH_BFD_SHARED:BOOL=OFF ^
  -DCTK_LIB_Core_WITH_BFD_STATIC:BOOL=OFF ^
  -DCTK_LIB_DICOM/Core:BOOL=ON ^
  -DCTK_LIB_DICOM/Widgets:BOOL=ON ^
  -DCTK_LIB_ImageProcessing/ITK/Core:BOOL=OFF ^
  -DCTK_LIB_PluginFramework:BOOL=OFF ^
  -DCTK_LIB_Scripting/Python/Core:BOOL=OFF ^
  -DCTK_LIB_Scripting/Python/Widgets:BOOL=OFF ^
  -DCTK_LIB_Visualization/VTK/Core:BOOL=ON ^
  -DCTK_LIB_Visualization/VTK/Widgets:BOOL=ON ^
  -DCTK_LIB_Visualization/VTK/Widgets_USE_TRANSFER_FUNCTION_CHARTS:BOOL=ON ^
  -DCTK_LIB_Widgets:BOOL=ON ^
  -DCTK_LIB_XNAT/Core:BOOL=OFF ^
  -DCTK_LIB_XNAT/Widgets:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.configadmin:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.dah.cmdlinemoduleapp:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.dah.core:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.dah.exampleapp:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.dah.examplehost:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.dah.host:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.dah.hostedapp:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.eventadmin:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.log:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.metatype:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.plugingenerator.core:BOOL=OFF ^
  -DCTK_PLUGIN_org.commontk.plugingenerator.ui:BOOL=OFF ^
  -DCTK_QT_VERSION:STRING=5 ^
  -DCTK_SOURCE_DIR:STATIC=C:/temp/CTK-src ^
  -DCTK_SUPERBUILD:BOOL=ON ^
  -DCTK_USE_CONTRIBUTED_PLUGINS:BOOL=OFF ^
  -DCTK_USE_GIT_PROTOCOL:BOOL=ON ^
  -DCTK_USE_KWSTYLE:BOOL=OFF ^
  -DCTK_USE_QTTESTING:BOOL=OFF ^
  -DCTK_USE_QVTKOPENGLWIDGET:BOOL=ON ^
  -DCTK_USE_SYSTEM_VTK:BOOL=ON ^
  -DDOCUMENTATION_TARGET_IN_ALL:BOOL=OFF ^
  -DVTK_BUILD_EXAMPLES:BOOL=OFF ^
  -DVTK_BUILD_TESTING:BOOL=OFF ^
  -DVTK_QT_VERSION:STRING=5^
  -DWITH_COVERAGE:BOOL=OFF
..\CTK

cmake --build . --config Release -- /m

**Comment by altaybrusan** [comment]
I guess I forgot something.

**Comment by altaybrusan** [comment]
Hi @jcfr ,
Do you have any suggestion on this issue? Does it have to do something with Qt version or compiling options?
Thanks

**Comment by altaybrusan** [comment]
Finally I found the problem. CTK DOES NOT WORK WITH Qt5.8. Return back to Qt5.7

**Comment by pieper** [comment]
I've been building Slicer with Qt 5.9 and 5.10 (mac) and CTK works without a problem.  Maybe you can try building Slicer and you will get a working CTK build that you can adapt to your needs.

**Comment by lassoan** [comment]
CTK with Qt 5.9 works well for me on Windows (in Slicer).

**Comment by altaybrusan** [comment]
@lassoan @pieper @jcfr ,Yep I tested this combination VTK9 ( with VTK_RENDERING_BACKEND= OpenGl2 & Module_vtkGuiSupportQtOpenGL=ON) and Qt 5.9 this time it is fine. I guess the issue that I had had two chances:
1- Visual Studio 2015 Win 64x
or
2- VTK is not compiled with required options

I put this note for anyone who has the same issue, just update to newer versions of Qt and VTK 
Qt: 5.9.4 with QtCreator 4.5.0 ( Based on Qt 5.10.0 (MSVC 2015, 64 bit) not available on the official site)
and 
VTK 9

**Comment by jcfr** [comment]
To summarize:
* error was `moc_ctkVTKMagnifyView.cpp: error C2061: syntax error: identifier 'QVTKWidget'`
* proposed solution: use a newer version of Qt

If anyone has a similar issue, please create a new report specifying: configure option and version of Qt allowing to reproduce the problem using a terminal.
