### ISSUE TITLE
Failed to build on linux (gcc 4.9, gentoo)

### ISSUE THREAD

**Issue by Heather** [commontk/CTK#588]
I'm getting errors:

ctkPluginArchiveSQL_p.h:60:37: error: expected `)` becfore `<` token

`ctkPluginArchiveSQL(QSharedPointer<ctkPluginArchiveSQL> old, int generation, `

and some more exceptions alike this. using Qt5, what is happening?

Thank you

**Comment by saschazelzer** [comment]
What version of Qt5 are you using exactly? There could be issues with Qt5.5.

**Comment by Heather** [comment]
@sankhesh Qt 5.5.0, it's my system qt there. Is it hard to fix bug and I should downgrade?

**Comment by Heather** [comment]
@sankhesh I think it could be simply done by  adding `#include <QObject>`

**Comment by saschazelzer** [comment]
Missing includes could indeed be a reason for your errors. I do not have a Qt5.5 build at hand. Do you mind making the necessary changes and sending a pull request?

**Comment by Heather** [comment]
@saschazelzer can't schedule it for now. Maybe one day
