### ISSUE TITLE
Compiling with gcc 4.7.1 fails

### ISSUE THREAD

**Issue by ricortiz** [commontk/CTK#238]
Error message:   'write' was not declared in this scope

The error occurs in the file: Libs/Core/ctkErrorLogModel.cpp line 164 in Linux.

The function: write() is a global and the compiler can't find it.  
Appart from this,  CTK builds fine with gcc 4.7.1 in my  system.
