### PR TITLE
fix build with Qt 5.5 ( close #588 )

### LINKED ISSUE #588: Failed to build on linux (gcc 4.9, gentoo)
I'm getting errors:

ctkPluginArchiveSQL_p.h:60:37: error: expected `)` becfore `<` token

`ctkPluginArchiveSQL(QSharedPointer<ctkPluginArchiveSQL> old, int generation, `

and some more exceptions alike this. using Qt5, what is happening?

Thank you

### PR DESCRIPTION
**Pull request by Heather**

### CODE REVIEW

**Comment by saschazelzer** [comment]
Great, thanks!
