### ISSUE TITLE
CTK with VTK7, VC2015 64x, qt 5.x

### ISSUE THREAD

**Issue by altaybrusan** [commontk/CTK#768]
Does the CTK support this configuration? If so, then can I ask to give some hint what should I change in cmake file? My tries was unsuccessful all.

Thanks

**Comment by jcfr** [comment]
Hi, 

In my [previous answer](https://github.com/commontk/CTK/issues/717#issuecomment-341736861), the generator should be specified as `Visual Studio 14 2015 Win64` for 64-bit build.

If you would like to build with Qt5, I instead suggest to use VTK8 instead of VTK7.

> can I ask to give some hint what should I change in cmake file?

To help you would have to share:
* a GitHub project allowing to reproduce the problem
* step to reproduce the problem (including exact list of CMake argument specified as `-DNAME_OF_ARG:TYPE=Value`

Hth
Jc

**Comment by altaybrusan** [comment]
Hi @jcfr,
First thanks for your response.
I had already successfully compiled the VTk7.1 and even I used it with some qt projects.
But my problem started is with CTK vtk-widgets.
I  need all widgets and libs that CTK comes with, which includes:
DICOM, VTK and CTK widgets themselvs

For this,on my cmake screen (version: 3.9.4) I checked \n

CTK_BUILD_QTDESIGNER_PLUGINS
CTK_ENABLE_DICOM
CTK_ENABLE_DICOMApplicationHosting
CTK_ENABLE_PluginFramework
CTK_LIB_Visualization/VTK/widgets
CTK_LIB_Visualization/VTK/Core
CTK_LIB_Widgets
CTK_LIB_DICOM/Widgets
CTK_ENABLE_Widgets
CTK_APP_ctkCommandLineModuleExplorer
CTK_APP_ctkDICOM
CTK_APP_ctkDICOM2
CTK_APP_ctkDICOMDemoSCU
CTK_APP_ctkDICOMHost
CTK_APP_ctkDICOMIndexer
CTK_APP_ctkDICOMObjectViewer
CTK_APP_ctkDICOMQuery
CTK_APP_ctkDICOMQueryRetrieve
CTK_APP_ctkDICOMRetrieve
CTK_APP_ctkEventBusDemo
CTK_APP_ctkExampleHost
CTK_APP_ctkExampleHostedApp
CTK_APP_ctkPluginBrowser
CTK_APP_ctkPluginGenerator
[...]

I start the configuration process  by pressing the configure button, and this gives
[...]
SuperBuild - CTK => Requires Log4Qt, ## **VTK**, DCMTK, QtSOAP, qxmlrpc, qRestAPI, CTKData, 
[...]

I found that this means, CTK will download a version of VTK (which I am not sure what it is) .
Now, the problem I have is that this vtk that is going to be downloaded during the cmake build time is not consistent with my configuration (i.e. visual studio VC++ 2015 64x, qt 5.8.0 and cmake 3.9). 
Two solution that I am thinking may solve the problem is

1- force the cmake to build CTK  with installed VTK ( in my case VTK7.1 has already built and installed on my computer) instead of downloading from the git and then force CTK to use it to make widgets during compile time. 

2- change the ctk cmake file(s) such that it downloads the most updated version (for example vtk8) instead of unknown pre-configured vtk version.

By considering all abovei @jcfr which method do you propose and how can I achieve?
By the way, Do I need ITK too? I do not installed the itk yet.


PS: during compile time this message shows up " microsoft c++ runtime invalid integer length modifier"
PSS: somewhere among the CTK make files I saw that that it has been written that the vtk-widgets has not been tested on VTK7. Please correct me if it is not.

Thanks in advance

**Comment by jcfr** [comment]
> CTK will download a version of VTK (which I am not sure what it is) .

To ensure CTK uses a VTK version consistent with you project, make sure to configure it setting `-DVTK_DIR:PATH=/path/to/your/VTK-build`

**Comment by altaybrusan** [comment]
Hi again @jcfr 
Thanks one more time.  I have done so (VTK_DIR is now added and path is set on VTK 8.0.1 release built), and most of the problems have been solved.
But still I got these new but few errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Undefined interface [C:\CTK\CTK-bin\CTK-build\Libs\PluginFramework\CTKPluginFramework.vcxproj]	CTK	C:\CTK\CTK-src\Libs\PluginFramework\ctkBasicLocation_p.h	35	

and

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'setImageData': is not a member of 'ctkVTKSliceView' [C:\CTK\CTK-bin\CTK-build\Libs\Visualization\VTK\Widgets\CTKVisualizationVTKWidgets.vcxproj]	CTK	C:\CTK\CTK-bin\CTK-build\Libs\Visualization\VTK\Widgets\moc_ctkVTKSliceView.cpp	150	

Do you have any idea what should I change?

Thanks

**Comment by altaybrusan** [comment]
I think the above problems have something to do with QtVTKWidget and/or QTVTKWidgetPlugin
Should I have to give its path to CMake
 ( i.e. C:\VTK\VTK-8-install\plugins\designer\QVTKWidgetPlugin.dll) 

because I see this weird message by CMake:

CMake Warning (dev) at C:/Qt/Qt5.8.0/5.8/msvc2015_64/lib/cmake/Qt5/Qt5ModuleLocation.cmake:4 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '${_qt5_install_prefix}/Qt5@module@/Qt5@module@Config.cmake'

  the old evaluation rules produce:

    'C:/Qt/Qt5.8.0/5.8/msvc2015_64/lib/cmake/Qt5/Qt5Config.cmake'

  but the new evaluation rules produce:

    'C:/Qt/Qt5.8.0/5.8/msvc2015_64/lib/cmake/Qt5@module@/Qt5@module@Config.cmake'

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  C:/Qt/Qt5.8.0/5.8/msvc2015_64/lib/cmake/Qt5/Qt5Config.cmake:25 (include)
  CMake/ctkMacroSetupQt.cmake:50 (find_package)
  CMakeLists.txt:418 (ctkMacroSetupQt)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by jcfr** [comment]
Hi,

> Error C2039 'setImageData': is not a member of 'ctkVTKSliceView'

Did you do  a clean build of CTK ? 

If you build against a newer VTK, it should not try to compile this code path.

See https://github.com/commontk/CTK/blob/695495c880e033318a383cd86f243fedbe35cebb/Libs/Visualization/VTK/Widgets/ctkVTKSliceView.h#L104-L108


> Error Undefined interface [C:\CTK\CTK-bin\CTK-build\Libs\PluginFramework\CTKPluginFramework.vcxproj] CTK C:\CTK\CTK-src\Libs\PluginFramework\ctkBasicLocation_p.h 35

Not sure what is the issue here.
 

> CMake Warning (dev) at C:/Qt/Qt5.8.0/5.8/msvc2015_64/lib/cmake/Qt5/Qt5ModuleLocation.cmake:4 

This warning can be ignored.

**Comment by altaybrusan** [comment]
Hi,
Ye, I saw this VTK_MAJOR_VERSION, but I am not sure how to pass it to the CMake. Better to say, should I have to make this variable too?
I just added the VTK_DIR. BTW, I did not installed dcmtk neither ITK, do I have to?
Thanks

**Comment by jcfr** [comment]
To move forward with your issue, it suggest that you provide a set of command allowing to reproduce the problem.

I suggest you copy here the set of commands used to download/configure/build VTK, and the set of command to download/configure/build CTK.

Using `ccmake` or `cmake-gui` is useful to quickly try option but it is not helpful to get a set command line options allowing to reproduce a particular build.

Consider providing here command line of the form:

```
git clone git://github.com/kitware/VTK
mkdir VTK-build
cd VTK-build
cmake -DQt5_DIR=/path/to/Qt5/... -DOption1:BOOL=ON .... -G "Visual Studio 14 2015 Win64" ../VTK
cmake --build . --config Release -- /m
```

```
git clone git://github.com/commontk/CTK
mkdir CTK-build
cd CTK-build
cmake -DQt5_DIR=/path/to/Qt5/... -DVTK_DIR:PATH=/path/to/VTK-build -DOption1:BOOL=ON .... -G "Visual Studio 14 2015 Win64" ../CTK
cmake --build . --config Release -- /m
```


> I did not installed dcmtk neither ITK, do I have to?

If you  enable DICOM support in CTK, DCMTK will indeed be useful 

Similarly if you enable the ImageProcess/ITK/Core module in CTK, ITK will be needed.


Looking at how CTK is configured in Slicer may provide you with useful information: https://github.com/Slicer/Slicer/blob/master/SuperBuild/External_CTK.cmake

**Comment by jcfr** [comment]
Out of curiosity, are you trying to integrate CTK in this project: https://github.com/altaybrusan/SimpleScanner

**Comment by altaybrusan** [comment]
First, thanks for your quick return :)
Ye I want to integrate it to this project (at first step)
After a non-stop trail for a week 
I got this error now

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2653	'QVTKWidget': is not a class or namespace name [C:\CTK\CTK-build\CTK-build\Libs\Visualization\VTK\Widgets\CTKVisualizationVTKWidgets.vcxproj]	CTK	C:\CTK\CTK-build\CTK-build\Libs\Visualization\VTK\Widgets\moc_ctkVTKChartView.cpp	199	

I am not sure if it has something to do with openGL or openGL2 (my VTK backend)
If you have any other suggestion Ill give it a try

Thanks

**Comment by altaybrusan** [comment]
I have cloned the VTK8.0.1 repository into **VTK-src** folder then using CMake I build it into  **VTK-bin** then using visual studio I started the "BUILD-ALL" project after successful build, I run the INSTALL project to put everything into  **VTK-install** folder
Then, as you said I added VTK_DIR and point it to the VTK-install folder
It did not work, changed it to the VTKbin, again failed and finally VTKsrc but failed again.
I also found this   CTK_USE_SYSTEM_VTK from the slicer template that you sent.
It forces the VTK_DIR to use the C:\VTK\VTK-8-install\cmake. 
In all cases  QVTKWidget is not found. 
❌ 

PS: I have set the parameters as slicer example.

**Comment by altaybrusan** [comment]
Not yet actually, I just recently found the CTK and just playing around to figure it out. But Ill upload a version.
Thanks for your time and commitment

**Comment by altaybrusan** [comment]
Finally I found the problem. CTK DOES NOT WORK WITH Qt5.8. Return back to Qt5.7

**Comment by jcfr** [comment]
xref #777 

To summarize, a newer version of Qt should be used.

**Comment by bingcaihuang** [comment]
Hi, altaybrusan, when i compile CTKPluginFramework use vs2015 ，i got this error, D:/VCTestProject/CTK/Libs/PluginFramework/ctkBasicLocation_p.h(35): error : Undefined interface 
and then i modify the code in ctkBasicLocation_p.h，
change
#include <service/datalocation/ctkLocation.h>
to
absolute path

then，compile and pass
i think that the cmake  could not find the containing path in CTKPluginFramework project，but i don't know how to modify the makefile
